apiVersion: v1
kind: Service
metadata:
  name: Argo-server
  labels:
    app: Argo-server

spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  