apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: help-svc-az-qa
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: az-qa
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: help-svc
    repoURL: ghcr.io/bentlynevada-bh
    targetRevision: 1.0.369
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
