apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: help-svc-s1e-uat-aws
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: aws-uat
    server: https://46F2AE048AAC6E32CF65B151628A55A5.gr7.us-east-1.eks.amazonaws.com
  project: default
  source:
    chart: help-svc
    helm:
      parameters:
        - name: autoscaling.enabled
          value: 'false'
    repoURL: ghcr.io/bentlynevada-bh
    targetRevision: 1.0.346
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
