name: pythonfile
on: [workflow_dispatch]
jobs:
  InstallPython:
    runs-on: ubuntu-latest
    steps:
      - name: InstallPython
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: cloneCode
        uses: actions/checkout@v2
      - name: installRequirements
        run: python3 insatll -r requirements.txt
      - name: runcode
        run: python3 main.py
