name: pythonfile
on: [workflow_dispatch]
jobs:
  InstallPython:
    runs-on: ubuntu-latest
    steps:
      - name: InstallPython
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: cloneCode
        uses: actions/checkout@v2

      - name: listFile
        id: test
        run: |
          echo "mix-test=$(mix test)\n" >> $GITHUB_OUTPUT
      - name: installRequirements
        run: |
          echo ${{steps.run_tests.outputs.*}}
          pip3 install -r requirements.txt

      - name: runcode
        run: python3 main.py
      - name: openFile
        run: |
          message=$(cat output.txt)
          echo ::warning title={Error In file}::${message}
      - name: uploadArtifact
        uses: actions/upload-artifact@v3
        with:
          path: output.txt
