name: pythonfile
on: [workflow_dispatch]
jobs:
  InstallPython:
    runs-on: ubuntu-latest
    steps:
      - name: InstallPython
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: cloneCode
        uses: actions/checkout@v2
      - name: listFile
        run: ls
      - name: installRequirements
        run: pip3 install -r requirements.txt
      - name: runcode
        run: python3 temp/main.py
