name: pythonfile
on: [workflow_dispatch]
jobs:
  InstallPython:
    runs-on: ubuntu-latest
    steps:
      - name: InstallPython
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: aws-cli
        run: |
          sudo curl -L -o install-aws.sh https://raw.githubusercontent.com/unfor19/install-aws-cli-action/master/entrypoint.sh && \
          sudo chmod +x install-aws.sh
          sudo ./install-aws.sh "v2" "amd64"
          sudo rm install-aws.sh
      - name: Configure AWS credentials from Production account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::339184560871:role/test
          aws-region: us-east-1
      - name: cloneCode
        uses: actions/checkout@v2
      - name: python as script
        run: |
          #!/usr/bin/env python3
          print("Hello")
#       - name: listFile
#         id: test
#         run: |
#           output="github"
#           echo "var=$output" >> $GITHUB_OUTPUT
#           echo "var2=foo" >> $GITHUB_OUTPUT
# #          echo $output >> $GITHUB_OUTPUT
# #          echo 'EOF' >> $GITHUB_OUTPUT
#       - name: installRequirements
#         run: |
#           echo ${{steps.test.outputs.var2}}
#           pip3 install -r requirements.txt

#       - name: runcode
#         run: python3 main.py
#       - name: openFile
#         run: |
#           message=$(cat output.txt)
#           echo ::warning title={Error In file}::${message}
#       - name: uploadArtifact
#         uses: actions/upload-artifact@v3
#         with:
#           path: output.txt
