name: test-alarm
on: [workflow_dispatch]
jobs:
  InstallPython:
    outputs:
      alarms: ${{ steps.matrix.outputs.alarm_data }}
    runs-on: ubuntu-latest
    steps:
      - name: aws-cli
        run: |
          sudo curl -L -o install-aws.sh https://raw.githubusercontent.com/unfor19/install-aws-cli-action/master/entrypoint.sh && \
          sudo chmod +x install-aws.sh
          sudo ./install-aws.sh "v2" "amd64"
          sudo rm install-aws.sh
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: "AKIAU56HZVLTYON7ZMHT"
          aws-secret-access-key: "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"
          aws-region: us-east-1
          mask-aws-account-id: 'no'
      - name: cloneCode
        uses: actions/checkout@v2
      - id: matrix
        run: |
          pip install boto3
          pip install requests
          output=$(python3 testalarm.py ${{ secrets.GH_TOKEN }})
          echo $output
          echo "alarm_data=$output" >> $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT
  build:
    needs: InstallPython
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJson(needs.InstallPython.outputs.alarms)}} # "${{ matrix.value.title }}"
    steps:
      - name: Create Github Issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ secrets.GH_TOKEN }}
          title: ${{ matrix.value.title }}
          body:  ${{ matrix.value.body }}
          labels: ["question"]


