name: pythonfile
on: [workflow_dispatch]
jobs:
  InstallPython:
    outputs:
      alarms: ${{ steps.getAlarms.outputs.alarm }}
    runs-on: ubuntu-latest
    steps:
      - name: cloneCode
        uses: actions/checkout@v2
      - id: getAlarms
        run: |
          echo "alarm=[]" >> $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT
      - name: Test
        if: ${{ steps.getAlarms.outputs.alarm_data != [] }}
        run: |
          echo "Hi"


